### ISSUE TITLE
use prisma as orm

### ISSUE THREAD

**Issue by Ali1Ammar** [RicardoRB/dartness#6]
there are amazing prisma client for dart is develop here 
https://github.com/odroe/prisma-dart
as it has full type-safety and it could connected into a lot of database 
it also used  the officially prisma engine
I think this framework should use this as it is orm

**Comment by RicardoRB** [comment]
Hi @Ali1Ammar thank you for creating the issue, I have been checking the prisma-dart and saw that you are contributor there. 

What makes prisma different from other ORMs?

 I have been thinking on using an ORM that is already been made it since there few there and create a new one may be a waste of time and effort, also if it is just using prisma, the user can easily add it as a dependency.

**Comment by Ali1Ammar** [comment]
@RicardoRB 
we at prisma_dart use the same official prisma engine that are used in prisma js/ts ,prisma golang and prisma python 
the dart client is just a interface that use this engine 
so this will decrease the error and bugs as the engine is already producing and used by a thousand of developers 

we generate the client based on ast coming from the engine this ast represents all the available functionality and there input output for each and we only create a dart class for this then sent the data to engine 
the engine is responsible of creating the query and connecting into the Database and get the output back into the dart client

also the power of prisma is that its a full type safety
it also supports all famous database
